#!/bin/bash
set -e

# Usage: step8-print-next-steps.sh <REPO_NAME> <COMPONENT_NAME> <BACKUP_BRANCH> <module1> <module2> ...

REPO_NAME="$1"
COMPONENT_NAME="$2"
BACKUP_BRANCH="$3"
shift 3
MODULES="$@"

echo "Step 8: Updating include directives..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  MANUAL STEP REQUIRED:"
echo ""
echo "You need to update include directives in the migrated .adoc files:"
echo ""
echo "In modules/*/pages/index.adoc files, change:"
echo "  include::master01-preface.adoc[]"
echo "To:"
echo "  include::xref:preface.adoc[]"
echo ""
echo "For UML class includes, change:"
echo "  include::../../UML/classes/LOCATABLE.adoc[]"
echo "To:"
echo "  include::ROOT:partial\$uml/LOCATABLE.adoc[]"
echo ""
echo "For UML diagram images, change:"
echo "  image::../UML/diagrams/diagram.svg[]"
echo "To:"
echo "  image::ROOT:uml/diagrams/diagram.svg[]"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Migration Summary                                         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Repository: $REPO_NAME"
echo "✓ Component:  $COMPONENT_NAME"
echo "✓ Modules:    $(echo $MODULES | wc -w)"
echo "✓ Backup branch: $BACKUP_BRANCH"
echo ""
echo "Next steps:"
echo "  1. Review the migrated structure in modules/"
echo "  2. Update include directives manually (see Step 8 above)"
echo "  3. Test build: make validate-structure REPO=$REPO_NAME"
echo "  4. Commit changes: git add . && git commit -m 'Migrate to Antora structure'"
echo ""
echo "To rollback: git checkout $BACKUP_BRANCH"
echo ""
