server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Legacy URL redirects
    include /etc/nginx/legacy-redirects.conf;

    location / {
        try_files $uri $uri/ =404;
    }
}
